name: Project deployment
on: workflow_dispatch
jobs:
  deploy-job:
    runs-on: Ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run npm install lib
        run: npm ci
      - name: execute lint
        run: npm run lint
