name: Project deployment
on: workflow_dispatch
env:
  MYSECRET: ${{secrets.SECRET_1}}
jobs:
  prebuild-test-job:
    runs-on: Ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run npm install lib
        run: npm ci
      - name: execute lint
        run: npm run lint
      - name: run test files
        run: |
          npm test
          echo ${{MYSECRET}}
  build-job:
    needs: prebuild-test-job
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run npm install lib
        run: npm ci
      - name: execute project build
        run: npm run build
